In [1]:
import pandas as pd

In [17]:
netflix_titles_df = pd.read_csv('MoviesOnStreamingPlatforms_updated.csv')

In [21]:
Ages = netflix_titles_df["Age"]
Ages = Ages.str.rstrip('+')
Ages

0         13
1         18
2         13
3          7
4         18
        ...
16739    NaN
16740      7
16741    NaN
16742    NaN
16743    NaN
Name: Age, Length: 16744, dtype: object

In [22]:
netflix_titles_df["Age"] = Ages

In [33]:
netflix_titles_df['Rotten Tomatoes'] = netflix_titles_df['Rotten Tomatoes']/100

In [35]:
clean_df = netflix_titles_df.drop(columns={"Unnamed: 0","ID", "Hulu","Prime Video","Disney+","Type", "IMDb"})
clean_df

,Title,Year,Age,Rotten Tomatoes,Netflix,Directors,Genres,Country,Language,Runtime
0,Inception,2010,13,87.0,1,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0
1,The Matrix,1999,18,87.0,1,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,136.0
2,Avengers: Infinity War,2018,13,84.0,1,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,149.0
3,Back to the Future,1985,7,96.0,1,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,116.0
4,"The Good, the Bad and the Ugly",1966,18,97.0,1,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,161.0
...,...,...,...,...,...,...,...,...,...,...
16739,The Ghosts of Buxley Hall,1980,NaN,NaN,0,Bruce Bilson,"Comedy,Family,Fantasy,Horror",United States,English,120.0
16740,The Poof Point,2001,7,NaN,0,Neal Israel,"Comedy,Family,Sci-Fi",United States,English,90.0
16741,Sharks of Lost Island,2013,NaN,NaN,0,Neil Gelinas,Documentary,United States,English,NaN
16742,Man Among Cheetahs,2017,NaN,NaN,0,Richard Slater-Jones,Documentary,United States,English,NaN
16743,In Beaver Valley,1950,NaN,NaN,0,James Algar,"Documentary,Short,Family",United States,English,32.0

In [36]:
clean_df = clean_df.dropna()
clean_df

,Title,Year,Age,Rotten Tomatoes,Netflix,Directors,Genres,Country,Language,Runtime
0,Inception,2010,13,87.0,1,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0
1,The Matrix,1999,18,87.0,1,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,136.0
2,Avengers: Infinity War,2018,13,84.0,1,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,149.0
3,Back to the Future,1985,7,96.0,1,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,116.0
4,"The Good, the Bad and the Ugly",1966,18,97.0,1,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,161.0
...,...,...,...,...,...,...,...,...,...,...
16657,A Kid in King Arthur's Court,1995,7,5.0,0,Michael Gottlieb,"Adventure,Comedy,Family,Fantasy,Romance","United States,Hungary,United Kingdom",English,89.0
16671,George of the Jungle 2,2003,7,17.0,0,David Grossman,"Adventure,Comedy,Family","United States,Australia",English,87.0
16677,That Darn Cat,1997,7,13.0,0,Robert Stevenson,"Comedy,Crime,Family,Thriller",United States,"English,French",116.0
16687,Kazaam,1996,7,6.0,0,Paul Michael Glaser,"Comedy,Family,Fantasy,Musical",United States,English,93.0
16705,Meet the Deedles,1998,7,7.0,0,Steve Boyum,"Comedy,Family",United States,English,93.0

In [37]:
filt = clean_df["Netflix"] == 1
filt

clean_df = clean_df.loc[filt,:]

In [40]:
clean_df.to_csv("Netflix_Rotten_Tomatoes_Scores.csv", index=False)

In [41]:
rotten_tomatoes_df = pd.read_csv('Netflix_Rotten_Tomatoes_Scores.csv')
rotten_tomatoes_df

,Title,Year,Age,Rotten Tomatoes,Netflix,Directors,Genres,Country,Language,Runtime
0,Inception,2010,13,87.0,1,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0
1,The Matrix,1999,18,87.0,1,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,136.0
2,Avengers: Infinity War,2018,13,84.0,1,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,149.0
3,Back to the Future,1985,7,96.0,1,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,116.0
4,"The Good, the Bad and the Ugly",1966,18,97.0,1,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,161.0
...,...,...,...,...,...,...,...,...,...,...
995,I Am Vengeance,2018,18,38.0,1,Ross Boyask,Action,United Kingdom,English,92.0
996,Beneath The Leaves,2019,18,20.0,1,Adam Marino,Thriller,United States,English,90.0
997,Viking Destiny,2018,18,13.0,1,David L.G. Hughes,"Action,Adventure,Fantasy","United Kingdom,Belgium",English,91.0
998,Black Rose,2014,18,22.0,1,Alexander Nevsky,"Action,Crime,Drama","Russia,United States","English,Russian",83.0
999,Mantra,2017,13,40.0,1,Nicholas Kharkongor,"Drama,Family",India,English,90.0